from tkinter import *

root = Tk()
root.title("Enigma")
# root.geometry("400X400")
# rotor position sliders and displaying on screen
pRotor1 = Scale(root, from_=1, to=26)
pRotor1.grid(row=0, column=7)
pRotor2 = Scale(root, from_=1, to=26)
pRotor2.grid(row=0, column=8)
pRotor3 = Scale(root, from_=1, to=26)
pRotor3.grid(row=0, column=9)
# rotor selection
var1 = IntVar()
var2 = IntVar()
var3 = IntVar()
var4 = IntVar()
var5 = IntVar()
r1c = Checkbutton(root, text="1", variable=var1)
r1c.grid(row=0, column=14)
r2c = Checkbutton(root, text="2", variable=var2)
r2c.grid(row=0, column=15)
r3c = Checkbutton(root, text="3", variable=var3)
r3c.grid(row=0, column=16)
r4c = Checkbutton(root, text="4", variable=var4)
r4c.grid(row=0, column=17)
r5c = Checkbutton(root, text="5", variable=var5)
r5c.grid(row=0, column=18)
# cypher keyboard
# toprow
cQ = Button(root, text="Q", padx=10, pady=10,bg="black",fg="White")
cQ.grid(row=1, column=0)
cW = Button(root, text="W", padx=10, pady=10,bg="black",fg="White")
cW.grid(row=1, column=2)
cE = Button(root, text="E", padx=10, pady=10,bg="black",fg="White")
cE.grid(row=1, column=4)
cR = Button(root, text="R", padx=10, pady=10,bg="black",fg="White")
cR.grid(row=1, column=6)
cT = Button(root, text="T", padx=10, pady=10,bg="black",fg="White")
cT.grid(row=1, column=8)
cY = Button(root, text="Y", padx=10, pady=10,bg="black",fg="White")
cY.grid(row=1, column=10)
cU = Button(root, text="U", padx=10, pady=10,bg="black",fg="White")
cU.grid(row=1, column=12)
cI = Button(root, text="I", padx=10, pady=10,bg="black",fg="White")
cI.grid(row=1, column=14)
c0 = Button(root, text="O", padx=10, pady=10,bg="black",fg="White")
c0.grid(row=1, column=16)
cP = Button(root, text="P", padx=10, pady=10,bg="black",fg="White")
cP.grid(row=1, column=18)
# middlerow
cA = Button(root, text="A", padx=10, pady=10,bg="black",fg="White")
cA.grid(row=2, column=1)
cS = Button(root, text="S", padx=10, pady=10,bg="black",fg="White")
cS.grid(row=2, column=3)
cD = Button(root, text="D", padx=10, pady=10,bg="black",fg="White")
cD.grid(row=2, column=5)
cF = Button(root, text="F", padx=10, pady=10,bg="black",fg="White")
cF.grid(row=2, column=7)
cG = Button(root, text="G", padx=10, pady=10,bg="black",fg="White")
cG.grid(row=2, column=9)
cH = Button(root, text="H", padx=10, pady=10,bg="black",fg="White")
cH.grid(row=2, column=11)
cJ = Button(root, text="J", padx=10, pady=10,bg="black",fg="White")
cJ.grid(row=2, column=13)
cK = Button(root, text="K", padx=10, pady=10,bg="black",fg="White")
cK.grid(row=2, column=15)
cL = Button(root, text="L", padx=10, pady=10,bg="black",fg="White")
cL.grid(row=2, column=17)
# lowerrow
cZ = Button(root, text="Z", padx=10, pady=10,bg="black",fg="White")
cZ.grid(row=3, column=2)
cX = Button(root, text="X", padx=10, pady=10,bg="black",fg="White")
cX.grid(row=3, column=4)
cC = Button(root, text="C", padx=10, pady=10,bg="black",fg="White")
cC.grid(row=3, column=6)
cV = Button(root, text="V", padx=10, pady=10,bg="black",fg="White")
cV.grid(row=3, column=8)
cB = Button(root, text="B", padx=10, pady=10,bg="black",fg="White")
cB.grid(row=3, column=10)
cN = Button(root, text="N", padx=10, pady=10,bg="black",fg="White")
cN.grid(row=3, column=12)
cM = Button(root, text="M", padx=10, pady=10,bg="black",fg="White")
cM.grid(row=3, column=14)
#space between 1st and second key
srow4 = Label(root,text="         ")
srow4.grid(row=4,column=0,columnspan=18)

#normal keyboard
#top row
nQ = Button(root, text="Q", padx=10, pady=10)
nQ.grid(row=5, column=0)
nW = Button(root, text="W", padx=10, pady=10)
nW.grid(row=5, column=2)
nE = Button(root, text="E", padx=10, pady=10)
nE.grid(row=5, column=4)
nR = Button(root, text="R", padx=10, pady=10)
nR.grid(row=5, column=6)
nT = Button(root, text="T", padx=10, pady=10)
nT.grid(row=5, column=8)
nY = Button(root, text="Y", padx=10, pady=10)
nY.grid(row=5, column=10)
nU = Button(root, text="U", padx=10, pady=10)
nU.grid(row=5, column=12)
nI = Button(root, text="I", padx=10, pady=10)
nI.grid(row=5, column=14)
n0 = Button(root, text="O", padx=10, pady=10)
n0.grid(row=5, column=16)
nP = Button(root, text="P", padx=10, pady=10)
nP.grid(row=5, column=18)
#middlerow
nA = Button(root, text="A", padx=10, pady=10)
nA.grid(row=6, column=1)
nS = Button(root, text="S", padx=10, pady=10)
nS.grid(row=6, column=3)
nD = Button(root, text="D", padx=10, pady=10)
nD.grid(row=6, column=5)
nF = Button(root, text="F", padx=10, pady=10)
nF.grid(row=6, column=7)
nG = Button(root, text="G", padx=10, pady=10)
nG.grid(row=6, column=9)
nH = Button(root, text="H", padx=10, pady=10)
nH.grid(row=6, column=11)
nJ = Button(root, text="J", padx=10, pady=10)
nJ.grid(row=6, column=13)
nK = Button(root, text="K", padx=10, pady=10)
nK.grid(row=6, column=15)
nL = Button(root, text="L", padx=10, pady=10)
nL.grid(row=6, column=17)
#bottomrow
nZ = Button(root, text="Z", padx=10, pady=10)
nZ.grid(row=7, column=2)
nX = Button(root, text="X", padx=10, pady=10)
nX.grid(row=7, column=4)
nC = Button(root, text="C", padx=10, pady=10)
nC.grid(row=7, column=6)
nV = Button(root, text="V", padx=10, pady=10)
nV.grid(row=7, column=8)
nB = Button(root, text="B", padx=10, pady=10)
nB.grid(row=7, column=10)
nN = Button(root, text="N", padx=10, pady=10)
nN.grid(row=7, column=12)
nM = Button(root, text="M", padx=10, pady=10)
nM.grid(row=7, column=14)
#space between keyboards
srow8 = Label(root,text="         ")
srow8.grid(row=8,column=0,columnspan=18)

#textboxes
clabel = Label(root,text="Encrypted Message")
clabel.grid(row=9,column=0,columnspan=18)

ctext = Entry(root,width=50,borderwidth=3)
ctext.grid(row=10,column=0,columnspan=18)

nlabel = Label(root,text="Normal Message")
nlabel.grid(row=11,column=0,columnspan=18)

ntext = Entry(root,width=50,borderwidth=3)
ntext.grid(row=12,column=0,columnspan=18)

root.mainloop()
